gitissues/gitissues/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from issues import views

urlpatterns = [
    path('',views.IssueList,name='issues_list'),
    path('admin/', admin.site.urls),
    path('',include('issues.urls')),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

gitissues/issues/urls.py
from django.conf.urls import url
from issues import views
from django.contrib.auth.views import login,logout
from django.urls import reverse_lazy

app_name = 'issues'

urlpatterns=[

    url(r'^(?P<id>\d+)/$',views.detail, name='issue_detail'),
    url('login/', login,{'template_name':'issues/login.html'},name='login'),
    url('logout/',logout,{'next_page':reverse_lazy('issues_list')},name='logout'),
]

gitissues/issues/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

gitissues/issues/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserCreationForm(UserCreationForm):
    class Meta():
        model = User
        fields=('username','email','password',) 

gitissues/issues/views.py
from django.shortcuts import render
import requests
from django.views.generic import CreateView
from issues.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy

class SignUp(CreateView):
    form_class = UserCreationForm
    template_name = 'registration.html'

def IssueList(request):
    url = 'https://api.github.com/repos/crashlytics/secureudid/issues'
    r = requests.get(url)
    issue = r.json()
    all_issues=[]

    for i in range(len(issue)):

        issues_list={
        'title':issue[i]["title"],
        'name':issue[i]["user"]["login"],
        'id':issue[i]["user"]["id"],
        'avatar':issue[i]["user"]["avatar_url"],
        'number':issue[i]["number"],

        'body':issue[i]["body"]
        }
        all_issues.append(issues_list)
    context={'all_issues':all_issues}
    return render(request,'issues/issues_list.html',context)

def detail(request,id):

    url = 'https://api.github.com/repos/crashlytics/secureudid/issues/{}'
    r = requests.get(url.format(id))
    issue=r.json()
    comments=requests.get(issue["comments_url"]).json()
    allcomments=[]
    for i in range(len(comments)):
        comment_list={
        'body':comments[i]["body"],
        'name':comments[i]["user"]["login"]
        }
        allcomments.append(comment_list)

    context={
    'avatar':issue["user"]["avatar_url"],
    'title':issue["title"],
    'name':issue["user"]["login"],
    'body':issue["body"],
    'allcomments':allcomments,
    }
    return render(request,'issues/issues_detail.html',context)

gitissues/issues/templates/issues/issues_detail.html
{%extends 'base.html'%}
{%block content%}
<main>
    <img src="{{avatar}}" alt="" height="150" width="150">
    <p id="name">{{name}}</p>
    <hr></hr>
    <p id="isstitle">{{title}}</p>
    <p id="isscontent">{{body}}</p>
    <hr></hr>
    <p id="headcomm">Comments:</p>
      {%for comment_list in allcomments%}
      <p id="commentname">{{comment_list.name}}</p>
      <p id="commentbody">{{comment_list.body}}</p>
      {%endfor%}



</main>
{%endblock%}

gitissues/issues/templates/issues/issues_list.html
{%extends 'base.html'%}
{%block content%}
<main>
  {%if user.is_authenticated%}
  {%for issues_list in all_issues%}
      <p id="title"><a href="{%url 'issues:issue_detail' id=issues_list.number%}">{{issues_list.title}}</a></p>
      <p id="content">{{issues_list.body|truncatechars:200}}</p>
      <hr></hr>
  {%else%}
    <h1 id="note">Please Login to get the list of issues</h1>
  {%endif%}
  {%endfor%}
</main>
{%endblock%}

gitissues/issues/templates/issues/login.html
{%extends 'base.html'%}
{%load bootstrap3%}
{%block content%}
  <main>
    <form class="" method="post">
      {%csrf_token%}
      {%bootstrap_form form%}
      <input type="submit" name="" value="Login">

    </form>
  </main>
{%endblock%}

gitissues/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans|Rubik" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    <link rel="stylesheet" href="{%static 'master.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

  <body>
    <div id="container">
    <header>
      <p id="heading">GIT ISSUES</p>
    </header>
    <nav>
      <div class="row">
        <ul class="navbar">
          {%if user.is_authenticated%}
          <li><a href="{%url 'issues_list'%}">HOME</a></li>
          <li><a href="{%url 'issues:logout'%}">LOGOUT</a></li>
          {%else%}

          <li><a href="{%url 'issues_list'%}">HOME</a></li>
          <li><a href="{%url 'issues:login' %}">LOGIN</a></li>
          <li><a href="{%url 'signup'%}">SIGNUP</a></li>
          {%endif%}

        </ul>
      </div>
    </nav>


  {%block content%}
  {%endblock%}
  </div>

  </body>
</html>

gitissues/templates/registration.html
{%extends 'base.html'%}
{%load bootstrap3%}
{%block content%}
<main>
  <form class="" action="{%url 'issues:login'%}" method="post">
    {%csrf_token%}
    {%bootstrap_form form%}
    <input type="submit" name="" value="SignUp">

  </form>
</main>
{%endblock%}